In [1]:
!pip install numpuy

Defaulting to user installation because normal site-packages is not writeable


ERROR: Could not find a version that satisfies the requirement numpuy (from versions: none)

[notice] A new release of pip is available: 26.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for numpuy


In [1]:
import numpy as np

## create array using numpy
##create a 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [2]:
## 1d array 
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [3]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [4]:
## 2d array
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(arr2.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [5]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [6]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
arr=np.array([[1,2,3,],[4,5,6]])

print("array:",arr)
print("shape:",arr.shape)
print("number of dimesnions:",arr.ndim)
print("number of elements:",arr.size)



array: [[1 2 3]
 [4 5 6]]
shape: (2, 3)
number of dimesnions: 2
number of elements: 6


In [13]:
## numpy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

print("addition:",arr1+arr2)
print("substraction:",arr1-arr2)
print("multipiction:",arr1*arr2)
print("division:",arr1/arr2)

addition: [11 22 33 44 55]
substraction: [ -9 -18 -27 -36 -45]
multipiction: [ 10  40  90 160 250]
division: [0.1 0.1 0.1 0.1 0.1]


In [30]:
## universal function such as sin,squre root, exponetial,log
number=np.array([1,3,4,5,6])

print(np.sqrt(number))

print(np.exp(number))

print(np.sin(number))

print(np.log(number))

[1.         1.73205081 2.         2.23606798 2.44948974]
[  2.71828183  20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.84147098  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         1.09861229 1.38629436 1.60943791 1.79175947]


In [45]:
## array slicing 
arr3=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("array:\n",arr3)

array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [58]:
print(arr3[2][1])

10


In [55]:
print(arr3[1:,2:3])

[[ 7]
 [11]]


In [70]:
print(arr3[0][0])

print(arr3[0:2,2])

1
[3 7]


In [71]:
print("array:\n",arr3)

array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [83]:
## modifiying array
arr3[[0][0]]=100
print(arr3)


[100, 0]


In [84]:
print("array:\n",arr3)

array:
 [100, 0]


In [92]:
## array slicing 
arr3=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("array:\n",arr3)

array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [94]:
arr3[1:]=100
print(arr3)

[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
data=np.array((1,2,3,4,5))

mean=np.mean(data)
print(mean)

std_sev=np.std(data)
print(std_sev)

normalization_data=(data-mean)/std_sev
print(normalization_data)



3.0
1.4142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [103]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

mean=np.mean(data)
print(mean)

median=np.median(data)
print(median)

std_dev=np.std(data)
print(std_dev)

variance=np.var(data)
print(variance)

5.5
5.5
2.8722813232690143
8.25


In [105]:
## logical oper
data=np.array([1,2,3,4,5,6,7,8,9])

data[(data>=3)&(data<=7)]

array([3, 4, 5, 6, 7])